### ISSUE TITLE
Checklist sebelum upload data

### ISSUE THREAD

**Issue by kartikadsiregar** [biodiversity-checklist/floraINA-peerkalbar#2]
- [ ] Administrasi function
- [x] Check batch upload dengan prefix database yang baru @ovancop 
- [ ] Check zip upload dengan prefix baru @widiw 
- [x] Check one by one dengan prefix baru
- [x] Check browse dengan prefix baru
