### ISSUE TITLE
Checklist untuk upload data

### ISSUE THREAD

**Issue by kartikadsiregar** [biodiversity-checklist/floraINA-peerkalbar#3]
- [x] Ganti DB server dengan db baru
- [ ] Check function semuanya
- [ ] Truncate data kalau ada data percobaan
- [x] Hapus direktori user
- [x] Hapus direktori image di public_assets

@ovancop

**Comment by ovancop** [comment]
Gaes dicoba di db yg baru ya fungsinya
